# Generated by Django 3.2.15 on 2022-09-18 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название товара'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Название заказа'),
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название скидки')),
                ('percent_off', models.IntegerField(verbose_name='Процент скидки')),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='discounts', to='api.order')),
            ],
        ),
    ]
