# Generated by Django 3.2.15 on 2022-09-18 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220918_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='api.order'),
        ),
    ]
