# Generated by Django 3.2.15 on 2022-09-18 13:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_discount_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.order'),
        ),
    ]
