# Generated by Django 3.2.15 on 2022-09-18 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20220918_1839'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='tax',
            new_name='taxes',
        ),
    ]
