# Generated by Django 3.2.15 on 2022-09-18 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_order_taxes'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(choices=[('RUB', 'Ruble'), ('USD', 'US Dollar')], default='RUB', max_length=3),
        ),
    ]
